{
 "title": "Reforger SAT",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reforger_sat_exporter_uptime_seconds",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Registered Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "reforger_sat_exporter_registered_entities",
     "legendFormat": "Entities"
    },
    {
     "expr": "reforger_sat_exporter_registered_groups",
     "legendFormat": "Groups"
    },
    {
     "expr": "reforger_sat_exporter_registered_systems",
     "legendFormat": "System"
    },
    {
     "expr": "reforger_sat_exporter_registered_tasks",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Players and AI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "reforger_sat_exporter_player_count",
     "legendFormat": "Players"
    },
    {
     "expr": "reforger_sat_exporter_ai_characters",
     "legendFormat": "AI Characters"
    }
   ]
  },
  {
   "title": "Server FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "reforger_sat_exporter_frames_per_second",
     "legendFormat": " "
    }
   ]
  }
 ]
}